### ISSUE TITLE
没有在编辑器里面提示错误信息呢

### ISSUE THREAD

**Issue by TingYinHelen** [lkiarest/eslint-plugin-vuefix#1]
我安装了`eslint-plugin-vuefix`，但是在编辑器里面`.vue`文件没有错误信息提示呢？我用的是atom编辑器，是必须要用sublime么，下面是我的.eslintrc.js

<img width="852" alt="screen shot 2017-01-05 at 10 41 36 am" src="https://cloud.githubusercontent.com/assets/14006826/21670334/4463549a-d34e-11e6-9d8d-8d248f3b6b3b.png">

**Comment by lkiarest** [comment]
`extends: 'vue' `
改成 
`extends: 'standard'`
