### ISSUE TITLE
修改的位置计算好像有问题

### ISSUE THREAD

**Issue by SilentTiger** [lkiarest/eslint-plugin-vuefix#2]
![image](https://cloud.githubusercontent.com/assets/764862/21715020/0d55f4d6-d43d-11e6-88b0-bda7686038f8.png)
如上图所示，自动插入的分号，位置都不太正确

**Comment by SilentTiger** [comment]
我好像找到问题的原因了，是因为我的Vue代码文件都是CRLF换行，改成LF换行就行了。
如果看到这个问题的人和我一样有很多文件需要改换行方式，可是试试我这个nodejs脚本

![image](https://cloud.githubusercontent.com/assets/764862/22614911/a9ebf03c-eac4-11e6-9343-6adb8d154015.png)

详情见附件
[index.js.txt](https://github.com/lkiarest/eslint-plugin-vuefix/files/751958/index.js.txt)

**Comment by lkiarest** [comment]
额，没发现这个问题。。回头我试下，感谢反馈哈

**Comment by lkiarest** [comment]
用新的计算方式处理，避免了这种问题

**Comment by Ttxy0105** [comment]
vscode mac版本还是有行数提示错误

**Comment by lkiarest** [comment]
@Ttxy0105 方便提供一下你有错误的文件不，我 == 试下~

**Comment by Ttxy0105** [comment]
[cargoInformation.vue.txt](https://github.com/lkiarest/eslint-plugin-vuefix/files/1336047/cargoInformation.vue.txt)
<img width="493" alt="ea1182e3-5d05-48ed-8b49-cbec61ffac47" src="https://user-images.githubusercontent.com/12410405/30899338-22b97e94-a325-11e7-8efa-7f769a921a7d.png">
是这样的，麻烦了

**Comment by lkiarest** [comment]
@Ttxy0105 这个问题已经修复了，可以更新到最新版本试试，~~ 不同的编辑器获取的行号还不一样
