### ISSUE TITLE
在vscode中修改的行数有问题

### ISSUE THREAD

**Issue by duosanglee** [lkiarest/eslint-plugin-vuefix#3]
@lkiarest 
![2017-04-17 10 50 06](https://cloud.githubusercontent.com/assets/7676981/25092442/488190c4-23c0-11e7-937d-d36fe5a5daf6.png)

**Comment by duosanglee** [comment]
我lf和crlf换行都试过了 都有问题

**Comment by duosanglee** [comment]
atom编辑器里也是这样

**Comment by lkiarest** [comment]
用新的计算方式处理，避免了这种问题，麻烦试下新的版本 0.1.1 应该没问题了
