### ISSUE TITLE
Not clear with eslint.autoFixOnSave in VSCode

### ISSUE THREAD

**Issue by lee-40square** [lkiarest/eslint-plugin-vuefix#5]
I just installed the plugin and added it to my .eslintrc.js file

```
plugins: [
    'html',
    'vuefix'
  ],
```

in my `settings.json` file I have `"eslint.autoFixOnSave": true`. It works for .js files but not for .vue files. Any idea why?

**Comment by lkiarest** [comment]
@lee-40square 
I have tried in the latest VS Code, and some settings should be customized as below:

In .eslintrc.js, add settings:
```
  plugins: [
    'html',
    'vuefix'
  ],
  settings: {
    "html/html-extensions": [".html"]
  },
```
and in VS Code settings.json, set language rule:
```
{
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        {
            "language": "vue"
        }
    ]
}
```
that's all ~~

**Comment by lee-40square** [comment]
Worked great. Thanks for the help. :-)
