### ISSUE TITLE
vue-cli3自动修复无效？

### ISSUE THREAD

**Issue by evansun1995** [lkiarest/eslint-plugin-vuefix#6]
使用vue内置eslint-standard，按照说明配置了vuefix后，不仅不能自动修复，而且还会让eslint对vue文件的检测失效。
经过试验，发现是只要配置了 plugins: [ 'vuefix']，vue文件的检测就会失效，如果只配置"vuefix/vuefix": [2, { "auto": true }]，会自动在启动项目的时候进行修复的工作。

**Comment by lkiarest** [comment]
vue-cli 3可以使用官方工具:
`npx vue-cli-service lint --fix`
